### ISSUE TITLE
Cursor of iText in RTL mode (originX == 'right')

### ISSUE THREAD

**Issue by YaakovHatam** [fabricjs/fabric.js#2374]
EDIT (17/05/2020)
-------------------------
Hello guyz, i have started to write the RTL version of iText, you can take the dist/favric.rtl.js in my forked repository, after i'll finish i will rewrite it and merge to fabric.js repository.

[https://github.com/YaakovHatam/fabric.js](https://github.com/YaakovHatam/fabric.js)
---------------------------------------

hello i made quick fix that allow the cursor behave like it should be in Right-to-Left texts.

in the function:

``` javascript
renderCursor: function(boundaries, ctx) {
```

i have replaces the code:

``` javascript
boundaries.left + leftOffset,
```

with:

``` javascript
this.originX === 'right' ? -boundaries.left - leftOffset : boundaries.left + leftOffset,
```

and now it works proper!

add:
and for the selection the change is:
in the function

``` javascript
renderSelection: function(chars, boundaries, ctx) {
```

instead

``` javascript
boundaries.left + lineOffset,
```

replace with

``` javascript
this.originX === 'right' ? -boundaries.left - boxWidth +lineOffset : boundaries.left + lineOffset,
```

**Comment by asturur** [comment]
i don t think right to left text is supported.

what language are you using?

**Comment by kob-e** [comment]
@asturur this fix will let you rtl version

**Comment by asturur** [comment]
i cannot see why originX should handle text direction.
if rtl.is supported should be supported with any originX and originY.

**Comment by kob-e** [comment]
@asturur i use the Hebrew/English languages, when the user want iText with hebrew i set the originX to right, but the cursor still work like left origin.

**Comment by asturur** [comment]
Because originX and originY influence just the position where top and left
are originated.
If we will support RTL languages we have to specify a property "this.rtl =
true"  we cannot base it on originX that has another meaning.

2015-07-30 13:18 GMT+02:00 yaakov hatam <notifications@github.com>:

**Comment by kob-e** [comment]
@asturur i will add the "rtl" property and will post my enhancement.

**Comment by asturur** [comment]
@kob-e did you ever completed this feature?

**Comment by asturur** [comment]
reference: #2673, #2766, #2825

**Comment by ThakurKarthik** [comment]
@YaakovHatam @asturur any work progress here?

**Comment by asturur** [comment]
no. Sadly no progress on RTL text at all

**Comment by ThakurKarthik** [comment]
The workaround @YaakovHatam  was mentioning at the beginning is not RTL right..it's just cursor manipulation to start from right.Even the text-align also does the same,it still have to be implemented like a css `direction : rtl ` style.Don't know if we can try this [algorithm](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics) .

**Comment by YaakovHatam** [comment]
Hello guyz, i have started to write the RTL version of iText, you can take the dist/favric.rtl.js in my forked repository, after i'll finish i will rewrite it and merge to fabric.js repository.

https://github.com/YaakovHatam/fabric.js

**Comment by asturur** [comment]
Hi @YaakovHatam you may want to open a PR early to gather feedback and comments about the code.

Thanks for trying!

**Comment by YaakovHatam** [comment]
Thanks @asturur - 
My plan is:
1. Get to the point where itext works with RTL fully
2. Rewrite the code within the classes of fabricjs

**Comment by asturur** [comment]
would be great if you share it earlier if you want to contribute it back. When is done and working going back and adapt things to fabricjs style may be hard.

**Comment by YaakovHatam** [comment]
@asturur I will deal with the RTL issues in the fabric.js . After 3 years of using this amazing library with Hebrew after doing a lot of fixes, I decided to contribute back.
For now, as you can see in the link: https://yaakovhatam.github.io/fabric.js/index.html
The RTL works, the arrow keys now work, the mixed text (Latin / Hebrew / Arabic) works properly. Now I fix that choice.
Once I will complete these basics I will discuss with you how to implement it in the source code.

**Comment by YaakovHatam** [comment]
It will be nice if the users here will give me some test cases

**Comment by MebDevelop** [comment]
It is not working as well. It's writing text in wrong place.

**Comment by MebDevelop** [comment]
And also cursor position is not correct

**Comment by amitmas** [comment]
Looks good, very nice work...
Except the wrong selection position, there is another problem that the text dissapear when scaling horizontally or vertically.

**Comment by mistriel** [comment]
@YaakovHatam are you going to complete this MR ?

**Comment by asturur** [comment]
We merged a basic implementation of RTL.
https://github.com/fabricjs/fabric.js/pull/7046

**Comment by mistriel** [comment]
Initial support was released in version 4.5.0

**Comment by vijaygurjar** [comment]
I am checking with RTL support in fabricjs and its look amazing, but i found one issue when manually set cursor at somewhere in middle in text editing mode and writing text then cursor location is not set properly.

**Comment by asturur** [comment]
Can you open an issue with a detailed description and a jsfiddle that show this problem, and this problem only?
a clean simple example.

**Comment by vijaygurjar** [comment]
Hello asturur
Thanks for your quick reply.
I made sample url : https://jsfiddle.net/vijaygurjar/cj8wy5xu/
edit text to set cursor middle of the text box and writing text but added characters not at right position. May be i am doing some mistake to set properties.

**Comment by mistriel** [comment]
From the snippet you created it seems that you are trying to write English (Latin) inside an `IText` that is set with text direction `rtl` now that wont work - you will need to set the text direction back to `ltr` in order to make it work as expected.

**Comment by igalya** [comment]
Another issue is when using RTL text and textAlign is 'center' or 'right'.
Cursor is behaving strange.

**Comment by asturur** [comment]
Did you try the latest master? i thought we fixed that.

**Comment by igalya** [comment]
4.6? yes.

**Comment by mistriel** [comment]
@asturur  it was not fixed. The only way to work with RTL (`direction == rtl`)  and cursor working as expected is to set `textAlign` to `right`. Otherwise cursor is not on the correct location.

**Comment by chiragbytes** [comment]
Hello @asturur 

I am having issue with charSpacing in hebrew selected texts, after applying charSpacing text got flipped.
I found similar issue on #6848 , later tha found to be linked here.

After upgrading fabricJS to 4.6.0 and using new property direction I am still facing the same issue.

FYI, I am using Angular 8 with fabric js in my project.

Here is my code that i am using for applying charSpacing.
` obj.set({ 'charSpacing': Math.ceil(Number(event.target.value)) });`


Thank you.

**Comment by igalya** [comment]
In 4.6 selection of RTL text, when it is aligned to center or right, didn't work.
I just tried upgrading to 5.2.4, and it seems to be all messed up  now.
When direction is set to 'rtl' the text is all messy. playing with OriginX Align doesn't help.
Am I'm missing something?

**Comment by faizux** [comment]
Is there any official RTL version yet?

**Comment by ShaMan123** [comment]
#7864

**Comment by oustr** [comment]
> @asturur I will deal with the RTL issues in the fabric.js . After 3 years of using this amazing library with Hebrew after doing a lot of fixes, I decided to contribute back. For now, as you can see in the link: https://yaakovhatam.github.io/fabric.js/index.html The RTL works, the arrow keys now work, the mixed text (Latin / Hebrew / Arabic) works properly. Now I fix the selection of text. Once I will complete these basics I will discuss with you how to implement it in the source code.

@YaakovHatam  Seems that your link is 404 now😥And I'm still confused whether the text selection problem of rtl text is fixed, as I found I couldn't select some part of a rtl text in fabricjs, because when I click at the middle of such a text the cursor is always at the right. Seems that you're working on the rtl problems and I wonder if this bug is fixed, the information and discussions here on github still confuse me a lot

**Comment by YaakovHatam** [comment]
@oustr It was a while ago and I don't know where the RTL issue currently stands in the project
Can you write down what the problem is specifically and I'll try to restore?
