### ISSUE TITLE
Empty Textbox is broken if page is zoomed-in in Chrome.

### ISSUE THREAD

**Issue by alidadasb** [fabricjs/fabric.js#5120]
An empty textbox is no longer editable (enters edit mode but can't type characters), if the browser (chrome) is zoomed in. 

## Version
2.3.0, 2.2.X

## Test Case
http://jsfiddle.net/alidadasb/aj9vgynh/

## Steps to reproduce

// 1- Zoom in 90%
// 2- delete the text within the textbox
// 3- click outside
// 4- click on empty textbox and try to type 
// It is not typing

## Expected Behavior
Be able to type

## Actual Behavior
It does not type the characters

**Comment by ahsanejaz22** [comment]
Any update on this one?

**Comment by asturur** [comment]
not yet, sorry.

**Comment by asturur** [comment]
So is a chrome only problem

**Comment by asturur** [comment]
http://jsfiddle.net/u3wx0vsp/5/

This rule fabricjs out, i reproduced the bug in plain JS. and is not canvas or weird logic related. It just does not work

**Comment by asturur** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=870966

please follow the bug there i'll close this issue.

**Comment by asturur** [comment]
they proposed a workaround, i m implementing it

**Comment by antucg** [comment]
Has this been fixed in any of the releases of fabric?
Thanks.

**Comment by asturur** [comment]
we worked around it in a version, is written in the changelog. Chrome did not fix the bug yet

**Comment by antucg** [comment]
Hi thanks for the reply, I don't see it in the changelog. Which version has this fix?
Thanks!!
