### ISSUE TITLE
SVG Image cropped with fabric.Image.fromURL

### ISSUE THREAD

**Issue by jonathan-roy** [fabricjs/fabric.js#5512]
## Version
2.4.6

## Test Case
https://jsfiddle.net/kbcn4mpd/

## Information about environment
Tested on Chrome 71.

## Steps to reproduce
See fiddle.
I try to add an image to the canvas, using `fabric.Image.fromURL()` or `new fabric.Image()`. This image is a SVG file but I don't want to be able to manipulate objects inside this SVG, I just need to manipulate this SVG as a whole image.

## Expected Behavior
The canvas should show the entire image (french flag).

## Actual Behavior
The image appears, but is cropped: we can only see the upper left corner. I you remove the canvas' `height` attribute, then it appears correctly but then I am not able to correctly size the canvas.

**Comment by RoeyMaor** [comment]
In fact, this exact cropping issue is relevant starting from 2.4.0 which introduced the breaking change.
My solution was to downgrade to 2.3.6 in the meantime. It appears to affect a large group of SVGs. For example, almost every svg from here: https://github.com/twitter/twemoji

**Comment by ikudosi** [comment]
@RoeyMaor Thank you for the advise of downgrading to 2.3.6. I was having issues loading SVGs there were converted from .ai files. After downgrading I am no longer having issues and I can finally move on with my life!

**Comment by asturur** [comment]
@RoeyMaor in your opinion which is the commit from 2.3.6 to 2.4.0 that introduced the bug?

**Comment by asturur** [comment]
https://jsfiddle.net/6gbq7kfv/  with 2.3.6 behaves same to me.

**Comment by RoeyMaor** [comment]
@asturur This is weird, when I use versions bigger than 2.3.6 many SVGs are messed up like this:
![capture](https://user-images.githubusercontent.com/16507852/52665986-aaed2e00-2f15-11e9-8ff8-169d09302fab.PNG)
and when using 2.3.6 they are fine:
![capture2](https://user-images.githubusercontent.com/16507852/52666019-ba6c7700-2f15-11e9-8990-7e3e7bbb3a02.PNG)
I am using the latest chrome. perhaps this is even not the same bug, I assumed it is since it appears as a cropping issue.

**Comment by 0ro** [comment]
@RoeyMaor If you add width and height attributes to svg then there will be no cropped
https://jsfiddle.net/DenBogdanov/0Luqkm2g/

**Comment by 0ro** [comment]
What behavior is expected without the SVG object size set?

**Comment by RoeyMaor** [comment]
@0ro This in itself is another bug, as the proportions for correct display should be inferred from the viewbox in case the width and the height aren't specified in the svg tag itself

**Comment by 0ro** [comment]
The latest version in which the test case in issue runs correctly is 1.7.22
https://jsfiddle.net/DenBogdanov/qr67an39/
Since version 2.0.0, svg images are cropped
https://jsfiddle.net/DenBogdanov/qr67an39/1/

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/53682829-f9fad780-3cf9-11e9-9df4-d7a643b3a1ee.png)

so this is a bug ^^^ and i think it can be fixed.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/53683040-945c1a80-3cfc-11e9-860b-e121366b77ed.png)

this way seems working, i wonder how to detect this beahviour by code. i have to apply to the clipPath the transformation of parent groups.

**Comment by asturur** [comment]
to solve this properly we need an overhauled parser.
Or we need to note down the partial transformation of an element when the clipPath is declared.
This is a note for me as soon as i have a couple of hours to dedicate to this fix.

Maybe is better to invest them in a new svg parser that maints groups

**Comment by RoeyMaor** [comment]
@asturur, If this is caused by not applying  transformations to clipPath, then as I said the bug was introduced by one of these commits: (before them it did not exist, tested with the same svg as you showed here):
ffe01ab
513233b
2a476e4

**Comment by tiptronic** [comment]
Will there be a fix for this? (or a new svg parser?? 😉 )

It works fine in Fabric 2.7.0 using Safari on the Mac, but not in Chrome (if that is important)

**Comment by tiptronic** [comment]
Here's what I get on Safari 12.0.1/Mac Fabric 2.7.0:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/80752/56573927-625f8a00-65c2-11e9-91b6-cb96d0b375d1.png">

Same code on Chrome 73.0.3683.75/Mac Fabric 2.7.0
<img width="267" alt="image" src="https://user-images.githubusercontent.com/80752/56574136-cd10c580-65c2-11e9-87b0-23376ce75341.png">

**Comment by asturur** [comment]
svg parser is one of the funny things for me, and one of the things i would like to work on.
Didn't have much time march and april for a series of reasons.
Fabric is still actively developed used and improved, but time is few.

**Comment by tiptronic** [comment]
Sounds familiar 😊 
Anyway - Fabric is a really cool thing (even if there are some things like the above). ❤️

**Comment by asturur** [comment]
Yeah consider that parsing an svg, with all the svg capabilities is a non trivial task. The more functionalities we enable from SVG the more weird combination arrives.
I'm very happy with the current state of svg parsing.

**Comment by tiptronic** [comment]
Me too! And - interestingly - the above results show fine in Safari, but wrong in Chrome; so it seems that (besides parsing svg) more thing are involved

**Comment by asturur** [comment]
for me is broken in the latest safari too
![image](https://user-images.githubusercontent.com/1194048/56849633-4d069a80-68f7-11e9-9ec3-20620785ece8.png)

**Comment by mbejda** [comment]
As of now, the workaround for me is to replace the SVG `matrix()` attribute with `rotate()`.

SVG contains `matrix()` attribute. 
<img width="146" alt="Screen Shot 2019-06-18 at 2 35 21 PM" src="https://user-images.githubusercontent.com/5429780/59710128-5cf37a00-91d6-11e9-9fd0-7b5fafeddb9b.png">

SVG `matrix()` attribute replaced with `rotate()`
<img width="134" alt="Screen Shot 2019-06-18 at 2 35 18 PM" src="https://user-images.githubusercontent.com/5429780/59710269-aa6fe700-91d6-11e9-83a5-2cb07f97bcef.png">


Here is a JSFiddle of those 2 SVG's. 

https://jsfiddle.net/8xy3u95r/3/

**Comment by TeslaFreak** [comment]
Has there been any progress on this? Looks like its been about 8 months since this was reported and seems like a pretty major issue thats still going on

**Comment by asturur** [comment]
if i remember correctly this requires a full new svg parser logic.

**Comment by mozillo** [comment]
I have same problems, just render parts of svg, not full of svg.

**Comment by satendra02** [comment]
Getting the same issue with version **2.4.6** when trying to load SVG using `fabric.Image.fromURL`

Is there any workaround?

Here is the fiddle
https://jsfiddle.net/satendra02nov/3p0uvsjr/6/

**Comment by TeslaFreak** [comment]
@satendra you can use fabric.util.loadsvgfromurl but that will give you a path object instead of an image. If you dont need it to be an image object, then this will at least load the full picture on canvas for you. Unfortunately all we can do right now.

**Comment by TeslaFreak** [comment]
I dont know why one parser works and the other doesnt, but would it be possible to use the loadsvgfromurl to get the path object and then convert it to an image after that? Or is that basically what image.fromurl is doing already? I havent looked at the parser code myself to see

**Comment by asturur** [comment]
image.fromUrl shoud draw the svg as an image, with no details loss on zoom and 0 compatibility issues.

The other creates a group of objects.

If you do not need to let someone else ungroup the group and manipulate every single path on the canvas, loading it as an image is a solution

**Comment by asturur** [comment]
i think this has been partially fixed.
Anyone has the SVG files that have been used in the screenshot in the thread?

**Comment by tiptronic** [comment]
this one? Or what do you mean?

https://github.com/twitter/twemoji/blob/gh-pages/svg/1f171.svg

**Comment by asturur** [comment]
yes this one is one of them. also the jester i need.

**Comment by tiptronic** [comment]
Sorry - I was off for a couple of days...
Here's the other one:
https://github.com/twitter/twemoji/blob/gh-pages/svg/1f0cf.svg

**Comment by asturur** [comment]
i think this problem has been solved in current master!

**Comment by ikudosi** [comment]
Still having issues with version latest version 3.5.1. The SVG below renders properly on 2.3.6 which is what I've been using for quite some time. 

[Test SVG Logo](https://swell-b2b.s3-us-west-2.amazonaws.com/cropped_on_latest_fabric.svg)
[Rendered fabric on 2.3.6](https://swell-b2b.s3-us-west-2.amazonaws.com/maui_fabric_2.3.6.png)
[Rendered fabric on 3.5.1](https://swell-b2b.s3-us-west-2.amazonaws.com/maui_fabric_3.5.1.png)

**Comment by asturur** [comment]
Not sure what is wrong because the images you provide are really small and i can't understand if something is rendered bad.

this is how latest fabric renders the object:
![image](https://user-images.githubusercontent.com/1194048/71314140-67bbef80-2443-11ea-8e37-ee200e5af9ff.png)

this is how the browser renders it:
![image](https://user-images.githubusercontent.com/1194048/71314155-c1241e80-2443-11ea-9f5c-eb6db95340b1.png)


The images looks very similar to me.

**Comment by ikudosi** [comment]
Hmm interesting - this is what I did even for a simple test and still came to same conclusion:

1. Go to [http://fabricjs.com/kitchensink](http://fabricjs.com/kitchensink).
2. Click on "Clear Canvas"
3. Go to "Load SVG"
4. Copy & Paste entire[SVG](https://swell-b2b.s3-us-west-2.amazonaws.com/cropped_on_latest_fabric.svg) content
5. Click on "Load as Group"

This is what I got as a result:
![maui_fabric 3 5 0_site_kitchensink](https://user-images.githubusercontent.com/5790073/71322471-d4f87080-2495-11ea-9abe-7c7309f162ef.png)

**Comment by asturur** [comment]
the website could not include last commits

**Comment by simoroma** [comment]
Any news on this? Still having similar issues.

**Comment by ikudosi** [comment]
> Any news on this? Still having similar issues.

Try version 2.3.6. I had issues as well but tried someone's recommendation above and problem got resolved. I haven't tried any newer version since then as if it ain't broke... don't fix.

**Comment by simoroma** [comment]
> Try version 2.3.6. I had issues as well but tried someone's recommendation above and problem got resolved. I haven't tried any newer version since then as if it ain't broke... don't fix.

Thanks.

I am using 4.3 "with gestures". I am actually using Twemojis. Adding width and height to the svg actually works. I am going to modify all Twemojis I use with a script then.

**Comment by asturur** [comment]
what are twemojis? are they free to use set of emojis?
I had the same problem with notoemoji and i ended up adding a width and height using SVGO

**Comment by simoroma** [comment]
Yes, it is a free set of emojis. Someone was mentioning it a the beginning of this thread. 

> It appears to affect a large group of SVGs. For example, almost every svg from here: https://github.com/twitter/twemoji

**Comment by Saqib92** [comment]
> Sourcefile is:
> 
> https://github.com/twitter/twemoji/blob/gh-pages/svg/1f171.svg
> 
> Here's what I get on Safari 12.0.1/Mac Fabric 2.7.0: <img alt="image" width="267" src="https://user-images.githubusercontent.com/80752/56573927-625f8a00-65c2-11e9-91b6-cb96d0b375d1.png">
> 
> Same code on Chrome 73.0.3683.75/Mac Fabric 2.7.0 <img alt="image" width="267" src="https://user-images.githubusercontent.com/80752/56574136-cd10c580-65c2-11e9-87b0-23376ce75341.png">
> 
> Please also note, that the second layer ('B') is not showing
> 
> If I let Fabric group the elements it looks like this: <img alt="image" width="267" src="https://user-images.githubusercontent.com/80752/56574470-9be4c500-65c3-11e9-96d1-ccf89315d53b.png">

fabricjs v5.2.1 (custom build from website for Eraser tool). 

Facing same issue but in Latest Safari MAC and IPhone. 

SVG are cropped when load from JSON.

**Comment by asturur** [comment]
i went on fabricjs.com/kitchensink where there is still fabricjs 5.2.1

i loaded that svg and json saved and restored it without issue

```
{
  "version": "5.2.1",
  "objects": [
    {
      "type": "group",
      "version": "5.2.1",
      "left": 60.25,
      "top": 54.25,
      "width": 47.5,
      "height": 47.5,
      "scaleX": 3.25,
      "scaleY": 3.25,
      "objects": [
        {
          "type": "path",
          "version": "5.2.1",
          "left": -23.13,
          "top": -23.13,
          "width": 36,
          "height": 36,
          "fill": "rgba(221,46,68,1)",
          "stroke": "",
          "scaleX": 1.25,
          "scaleY": 1.25,
          "flipY": true,
          "clipPath": {
            "type": "path",
            "version": "5.2.1",
            "originX": "left",
            "originY": "top",
            "left": -19.5,
            "top": -19.5,
            "width": 38,
            "height": 38,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "backgroundColor": "",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "path": [
              [
                "M",
                0,
                38
              ],
              [
                "L",
                38,
                38
              ],
              [
                "L",
                38,
                0
              ],
              [
                "L",
                0,
                0
              ],
              [
                "L",
                0,
                38
              ],
              [
                "Z"
              ]
            ],
            "inverted": false,
            "absolutePositioned": false
          },
          "path": [
            [
              "M",
              0,
              0
            ],
            [
              "C",
              0,
              -2.209,
              -1.791,
              -4,
              -4,
              -4
            ],
            [
              "L",
              -32,
              -4
            ],
            [
              "C",
              -34.209,
              -4,
              -36,
              -2.209,
              -36,
              0
            ],
            [
              "L",
              -36,
              28
            ],
            [
              "C",
              -36,
              30.209,
              -34.209,
              32,
              -32,
              32
            ],
            [
              "L",
              -4,
              32
            ],
            [
              "C",
              -1.791,
              32,
              0,
              30.209,
              0,
              28
            ],
            [
              "L",
              0,
              0
            ],
            [
              "Z"
            ]
          ]
        },
        {
          "type": "path",
          "version": "5.2.1",
          "left": -10,
          "top": -14.47,
          "width": 16.06,
          "height": 22.08,
          "fill": "rgba(255,255,255,1)",
          "stroke": "",
          "scaleX": 1.25,
          "scaleY": 1.25,
          "flipY": true,
          "clipPath": {
            "type": "path",
            "version": "5.2.1",
            "originX": "left",
            "originY": "top",
            "left": -20.03,
            "top": -19.54,
            "width": 38,
            "height": 38,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "backgroundColor": "",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "path": [
              [
                "M",
                0,
                38
              ],
              [
                "L",
                38,
                38
              ],
              [
                "L",
                38,
                0
              ],
              [
                "L",
                0,
                0
              ],
              [
                "L",
                0,
                38
              ],
              [
                "Z"
              ]
            ],
            "inverted": false,
            "absolutePositioned": false
          },
          "path": [
            [
              "M",
              0,
              0
            ],
            [
              "L",
              3.659,
              0
            ],
            [
              "C",
              5.333,
              0,
              6.574,
              0.961,
              6.574,
              2.697
            ],
            [
              "C",
              6.574,
              4.155,
              5.457,
              5.147,
              3.287,
              5.147
            ],
            [
              "L",
              0,
              5.147
            ],
            [
              "L",
              0,
              0
            ],
            [
              "Z"
            ],
            [
              "M",
              0,
              9.24
            ],
            [
              "L",
              2.419,
              9.24
            ],
            [
              "C",
              3.9379999999999997,
              9.24,
              4.93,
              10.139,
              4.93,
              11.689
            ],
            [
              "C",
              4.93,
              13.146,
              3.7829999999999995,
              13.891,
              2.4189999999999996,
              13.891
            ],
            [
              "L",
              0,
              13.891
            ],
            [
              "L",
              0,
              9.24
            ],
            [
              "Z"
            ],
            [
              "M",
              -4.65,
              15.658000000000001
            ],
            [
              "C",
              -4.65,
              17.146,
              -3.6270000000000007,
              17.983,
              -2.2010000000000005,
              17.983
            ],
            [
              "L",
              3.752,
              17.983
            ],
            [
              "C",
              6.976,
              17.983,
              9.582,
              15.813,
              9.582,
              12.526
            ],
            [
              "C",
              9.582,
              10.356,
              8.681000000000001,
              8.898,
              6.697000000000001,
              7.968999999999999
            ],
            [
              "L",
              6.697000000000001,
              7.906
            ],
            [
              "C",
              9.333000000000002,
              7.534,
              11.41,
              5.333,
              11.41,
              2.636
            ],
            [
              "C",
              11.41,
              -1.7359999999999998,
              8.496,
              -4.093,
              4.216,
              -4.093
            ],
            [
              "L",
              -2.17,
              -4.093
            ],
            [
              "C",
              -3.597,
              -4.093,
              -4.65,
              -3.193,
              -4.65,
              -1.7359999999999998
            ],
            [
              "L",
              -4.65,
              15.657999999999998
            ],
            [
              "z"
            ]
          ]
        }
      ]
    }
  ]
}
```
