### ISSUE TITLE
On trying to load objects on canvas using "loadFromJson", operation fails due to image object issue( If image fails to load from provided URL).

### ISSUE THREAD

**Issue by fabricDev** [fabricjs/fabric.js#5532]
## Version
1.7.11

## Test Case
http://jsfiddle.net/wogz73y2/5/

## Information about environment
Browser

## Steps to reproduce
Create a group of objects with image. ( Set src property to some invalid url to reproduce issue)
Try to load them on canvas using "loadFromJson" method.
For more details check the fiddle : http://jsfiddle.net/wogz73y2/5/
## Expected Behavior
Objects other than image should load on canvas.

**Comment by asturur** [comment]
This problem has been resolved on newer versions of fabricJS. 1.7.11 is unsupported

**Comment by fabricDev** [comment]
Issue persists on even latest version of fabric js (2.7.0) - http://jsfiddle.net/wogz73y2/5/

**Comment by asturur** [comment]
May it be that is not supported recursively yet.

**Comment by jameswel** [comment]
I have the same problem. Is there any version where it works ?

**Comment by asturur** [comment]
need to see if i can verify the bug and fix it.
