### ISSUE TITLE
textBox set("fontFamily","...") doesn't work

### ISSUE THREAD

**Issue by tttleon** [fabricjs/fabric.js#6832]
## Version
3.6.0

## Test Case
https://jsfiddle.net/tttleon/y2omb5qh/26/

## Information about environment
browser
chrome

## Steps to reproduce
```
//i use set to change textBox fontFamily prop ,but it doesnt work 
//only when change the color at the same time, can fontFamily change successfully

/*change failed*/
currentObj.set('fontFamily', 'Potta One') 

/*change success*/
currentObj.set('fill','red')
currentObj.set('fontFamily', 'Potta One');
```
## Expected Behavior
fontFamily changed failed
## Actual Behavior
fontFamily changed success

**Comment by asturur** [comment]
This is a bug solved with a recent commit:
bd2d3226b8ef8d456d9222b7c89a08b98a065f8d

**Comment by tttleon** [comment]
> This is a bug solved with a recent commit:
> [bd2d322](https://github.com/fabricjs/fabric.js/commit/bd2d3226b8ef8d456d9222b7c89a08b98a065f8d)
sorry i wrote the wrong version above ...and i m sure i m using the latest version and so the TEST CASE is,but this problem still exists
![image](https://user-images.githubusercontent.com/66937093/105734842-07fd1580-5f6e-11eb-9158-91ee6a431346.png)
![image](https://user-images.githubusercontent.com/66937093/105734901-13e8d780-5f6e-11eb-93fa-1ec0c1d06536.png)

**Comment by tttleon** [comment]
@asturur 
sorry i wrote the wrong version above ...and i m sure i m using the latest version and so the TEST CASE is,but this problem still exists
![image](https://user-images.githubusercontent.com/66937093/105735323-88bc1180-5f6e-11eb-8231-b41ca6377587.png)
![image](https://user-images.githubusercontent.com/66937093/105735336-8c4f9880-5f6e-11eb-9fe1-87af72e67786.png)

**Comment by asturur** [comment]
The fix is unpublished. should be 4.3.1
I can publish it for you later today.

**Comment by tttleon** [comment]
@asturur thank you  ,i just noticed its unpublished.   谢谢~
![image](https://user-images.githubusercontent.com/66937093/105736139-6f679500-5f6f-11eb-89ce-dff807eb2645.png)

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/releases/tag/v4.3.1

published!
